### ISSUE TITLE
Great Package

### ISSUE THREAD

**Issue by mshd** [wvanderp/iwf#3]
Hey Wouter,

great package, glad I found this.
I'm working on something similar, actually mapping all properties to the specific SnakType.

Let's get in touch.
https://t.me/martinwi22
Martin

**Comment by wvanderp** [comment]
Hello,

Thanks for the prase.

I have a similar project that is aimed at using the wiki data properties.
https://github.com/wvanderp/wikidata-properties

You can use it as inspiration or as is.

-wvdp
